name: test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Yarn at the correct version
        run: yarn set version 3.3.0
      - name: Install yarn dependencies
        uses: borales/actions-yarn@v3
        with:
          cmd: install
      - name: Run test suite
        uses: borales/actions-yarn@v3
        with:
          cmd: test
